output = "./internal/db/models"

[psql]
    dbname = "fiberlearn"
    host   = "localhost"
    port   = 5432
    user   = "postgres"
    pass   = "postgres"
    sslmode = "disable"
    schema  = "public"
    blacklist = ["schema_migrations"]